"""Agent instructions export for vibecode."""

from __future__ import annotations

import sys
from pathlib import Path

AGENTS_MARKER_START = "<!-- vibecode:agents:start -->"
AGENTS_MARKER_END = "<!-- vibecode:agents:end -->"
AGENTS_GENERATED_PATH = Path(".vibecode") / "generated" / "AGENTS.generated.md"
AGENTS_ROOT_PATH = Path("AGENTS.md")


def render_agents_block() -> str:
    """Return the vibecode agent instructions block (without markers)."""
    return (
        "# Agent Instructions\n\n"
        "> Generated by Vibecode. Primary source of truth: `.vibecode/`.\n\n"
        "## Before you start\n\n"
        "1. Read `.vibecode/current/context_pack.md` for the active task context.\n"
        "2. Read `.vibecode/architecture/INVARIANTS.md` and"
        " `.vibecode/architecture/MODULE_BOUNDARIES.md`.\n"
        "3. Read `.vibecode/handoff/NOW.md` for the current handoff.\n\n"
        "## Rules\n\n"
        "- Do not perform unrelated refactors.\n"
        "- Do not modify protected files without an explicit task.\n"
        "- Do not update README outside marked generated blocks.\n"
        "- Run required checks before finalizing changes.\n"
        "- Update the handoff document when done.\n"
    )


def render_agents_file() -> str:
    """Return AGENTS.md content wrapped in vibecode marker blocks."""
    block = render_agents_block()
    return f"{AGENTS_MARKER_START}\n{block}{AGENTS_MARKER_END}\n"


def _is_vibecode_managed(content: str) -> bool:
    """Return True if the file contains vibecode agent marker blocks."""
    return AGENTS_MARKER_START in content and AGENTS_MARKER_END in content


def _update_marker_block(existing: str, new_block: str) -> str:
    """Replace the vibecode marker block in *existing* with updated *new_block*."""
    start_idx = existing.index(AGENTS_MARKER_START)
    end_idx = existing.index(AGENTS_MARKER_END) + len(AGENTS_MARKER_END)
    replacement = f"{AGENTS_MARKER_START}\n{new_block}{AGENTS_MARKER_END}"
    return existing[:start_idx] + replacement + existing[end_idx:]


def write_agents_export(repo_root: Path, force: bool = False) -> tuple[Path, Path | None]:
    """Write agent instructions; return (generated_path, agents_md_path | None).

    Always writes to .vibecode/generated/AGENTS.generated.md.
    Also writes AGENTS.md in the repo root, unless it already exists and is
    not Vibecode-managed (in which case it is skipped unless *force* is True).
    """
    root = repo_root.resolve()

    generated_path = root / AGENTS_GENERATED_PATH
    generated_path.parent.mkdir(parents=True, exist_ok=True)
    block = render_agents_block()
    generated_path.write_text(block, encoding="utf-8")

    agents_md = root / AGENTS_ROOT_PATH
    agents_md_written: Path | None = None
    wrapped = render_agents_file()

    if not agents_md.exists():
        agents_md.write_text(wrapped, encoding="utf-8")
        agents_md_written = agents_md
    else:
        existing = agents_md.read_text(encoding="utf-8")
        if _is_vibecode_managed(existing):
            agents_md.write_text(_update_marker_block(existing, block), encoding="utf-8")
            agents_md_written = agents_md
        elif force:
            agents_md.write_text(wrapped, encoding="utf-8")
            agents_md_written = agents_md

    return generated_path, agents_md_written


def cmd_export_agents(args) -> int:
    repo_root = Path(args.repo_root).resolve()
    force: bool = getattr(args, "force", False)

    generated_path, agents_md_path = write_agents_export(repo_root, force=force)
    print(f"Agents export written: {generated_path}", file=sys.stderr)

    if agents_md_path:
        print(f"AGENTS.md written: {agents_md_path}", file=sys.stderr)
    else:
        agents_md = repo_root / AGENTS_ROOT_PATH
        if agents_md.exists():
            print(
                "AGENTS.md exists and is not Vibecode-managed; skipped"
                " (use --force to overwrite).",
                file=sys.stderr,
            )

    return 0
